name: Update RSS Feeds
on:
  push:
    branches: [main]
  # Triggers the workflow every 4 hours (15 mins past)
  schedule:
    - cron: "15 */4 * * *"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 'feed/requirements.txt'
      - name: Run Python script
        run: python 'feed/get_feeds.py'
      - name: Commit and push changes
        run: |
          git config user.email "tjlawren@gmail.com"
          git config user.name "tlawrence36"
          # git config --global user.name "GitHub Actions"
          # git config --global user.email "no-reply@github.com"
          git add .
          git commit -m "Update JSON feeds (automated)"
          git push origin main